# Generated by Django 4.2.7 on 2023-12-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='address_line_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='address_line_2',
            new_name='address_2',
        ),
    ]
