# Generated by Django 4.2.7 on 2023-12-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_address_line_1_user_profile_address_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
