# Generated by Django 4.2.7 on 2024-01-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user_name',
        ),
    ]
