# Generated by Django 4.2.7 on 2024-01-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_address_1_user_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='state',
            field=models.CharField(blank=True, default=True, max_length=15, null=True),
        ),
    ]
