# Generated by Django 4.2.7 on 2024-01-24 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='phone',
            field=models.BigIntegerField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
