# Generated by Django 4.2.7 on 2024-01-28 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('accounts', '0011_delete_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon'),
        ),
    ]
