# Generated by Django 4.2.7 on 2024-01-29 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_profile_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='state',
        ),
    ]
