# Generated by Django 4.2.7 on 2024-02-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_address_phone_alter_user_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
