# Generated by Django 4.2.7 on 2023-12-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productvariant_is_active'),
        ('outgoing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ManyToManyField(blank=True, to='products.productvariant'),
        ),
    ]
