

"""
Django settings for purpleshop project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os

from decouple import config
from pathlib import Path
from django.contrib.messages import constants as messages


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')



DEBUG = config('DEBUG', cast=bool,default=True)

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '13.50.108.30', 'purpleshop.tech', 'www.purpleshop.tech']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'products',
    'accounts',
    'adminpanel',
    'adminpanel.templatetags',
    'outgoing',
    'orders',
    'users',
    'coupon',

    'corsheaders',
]


CORS_ALLOWED_ORIGINS = [ "http://localhost:8000", "http://13.50.108.30", "http://13.50.108.30:*", 'http://www.purpleshop.tech', 'http://purpleshop.tech']

# Allow all headers and methods for simplicity, adjust based on your requirements
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'purpleshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'products.context_processors.menu_links',
                'outgoing.context_processors.counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'purpleshop.wsgi.application'



# Password validation


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
  },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True




DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE', default='django.db.backends.postgresql'),
        'NAME': config('DB_NAME', default=''),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default=''),
        'PORT': config('DB_PORT', default=''),
    }
}


# database for hosting-----------

# DATABASES = {

#             'default': {
#             'ENGINE': 'django.db.backends.postgresql_psycopg2',
#             'NAME': 'myproject',
#             'USER': 'myprojectuser',
#             'PASSWORD': 'password',
#             'HOST': 'localhost',
#             'PORT': '5432',
#             }
#             }



# database for hosting-----------




# media files configurations
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"




# static for host-----------

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# static for host-----------



STATIC_URL = '/static/'
STATICFILES_DIRS = [
   os.path.join(BASE_DIR, 'static'),
]





MESSAGE_TAGS = {
    messages.ERROR: "danger",
}


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'purpleshop.tech@gmail.com'
EMAIL_HOST_PASSWORD = 'eiqixfashnaqqqcy'




SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"



DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
