# Generated by Django 4.2.7 on 2024-02-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image', models.ImageField(upload_to='photos/banner')),
                ('login_image', models.ImageField(upload_to='photos/banner')),
            ],
        ),
    ]
