# Generated by Django 4.2.7 on 2023-12-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
    ]
