# Generated by Django 4.2.7 on 2023-12-20 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_first_name_remove_order_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'New'), (2, 'Accepted'), (3, 'Preparing'), (4, 'OnShipping'), (5, 'Completed'), (6, 'Canceled'), (7, 'Return')], default=True, max_length=10),
        ),
    ]
