# Generated by Django 4.2.7 on 2023-12-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_tracking_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_no',
        ),
    ]
