# Generated by Django 4.2.7 on 2023-12-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='user_note',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
