# Generated by Django 4.2.7 on 2023-12-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productvariant_quantity'),
        ('orders', '0016_orderproduct_user_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('OnShipping', 'On Shipping'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('Return', 'Return')], default='New', max_length=10),
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='product_variant',
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product_variant',
            field=models.ManyToManyField(blank=True, to='products.productvariant'),
        ),
    ]
