# Generated by Django 4.2.7 on 2024-01-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('OnShipping', 'On Shipping'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Return', 'Return')], default='New', max_length=10),
        ),
    ]
