# Generated by Django 4.2.7 on 2024-02-01 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_order_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'New'), (2, 'Accepted'), (3, 'Preparing'), (4, 'On Shipping'), (5, 'Completed'), (6, 'Cancelled'), (7, 'Return')], default='New', max_length=10),
        ),
    ]
