# Generated by Django 4.2.7 on 2024-02-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_remove_order_order_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Return', 'Return'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
    ]
