# Generated by Django 4.2.7 on 2024-02-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_orderproduct_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address_2',
        ),
    ]
