# Generated by Django 4.2.7 on 2023-12-06 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
