# Generated by Django 4.2.7 on 2023-12-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
