# Generated by Django 4.2.7 on 2024-02-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_productvariant_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
